# syntax=docker/dockerfile:1.6
## base image ref: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-jetpack
## FROM nvcr.io/nvidia/l4t-jetpack:r36.3.0
 FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
SHELL ["/bin/bash", "-c"]
##RUN apt update && apt install -y gcc-9 g++-9


##RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 && \
##    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
## <install ROS2 humble>
## ref: https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debs.html

## setup timezone (KST)
RUN echo 'Asia/Seoul' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

## set locale
RUN apt update && apt install locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8

## setup sources (robust: try HTTPS, fallback to HTTP)
# setup sources (HTTP 고정 버전)
RUN set -eux; \
  apt-get update; \
  apt-get install -y --no-install-recommends ca-certificates curl gnupg software-properties-common; \
  add-apt-repository -y universe; \
  rm -f /usr/share/keyrings/ros-archive-keyring.gpg; \
  curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg; \
  # <-- 핵심: http 로 명시
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu \
  $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
    > /etc/apt/sources.list.d/ros2.list; \
  apt-get update


RUN set -eux; \
  apt-get install -y --no-install-recommends \
    ros-humble-desktop ros-dev-tools sudo vim git python3-pip; \
  rm -rf /var/lib/apt/lists/*

## install ROS2 packages and etc
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ros-humble-desktop \
        ros-dev-tools \
        sudo vim git \
        python3-pip; \
    rm -rf /var/lib/apt/lists/*

## laser_proc (urg_node2 의존) - APT로 설치
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends ros-humble-laser-proc; \
    rm -rf /var/lib/apt/lists/*

## bootstrap rosdep
RUN rosdep init

## </install ROS2 humble>

# deprecated
## install python3.8, venv
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.8 python3.8-venv python3.8-dev && \
    rm -rf /var/lib/apt/lists/*

## arguments about user
ARG UID=1000
ARG UNAME=misys
ARG PW=root

## create user based on user of host
RUN useradd -u $UID -m -s /bin/bash $UNAME && \
    echo $UNAME:$PW|chpasswd && \
    usermod -aG sudo $UNAME && \
    echo "$UNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

## change root user to new user && prepare to use packages
USER $UNAME
WORKDIR /home/$UNAME
RUN sudo apt-get update && rosdep update && mkdir -p f1tenth_ws/src

#### dummy command for update ####
RUN echo "__update__"
##################################

### <install drivers>

### install dependencies
RUN cd f1tenth_ws/src && \
    # git clone https://github.com/ros/diagnostics.git && \
    git clone https://github.com/ros-drivers/transport_drivers.git && \
    git clone https://github.com/flynneva/udp_msgs.git && \
    git clone https://github.com/f1tenth/ackermann_mux.git && \
    git clone https://github.com/ros-teleop/teleop_tools.git && \
    git clone https://github.com/f1tenth/vesc.git -b ros2

### install hokuyo lidar driver
RUN cd f1tenth_ws/src && \
    git clone --recursive https://github.com/Hokuyo-aut/urg_node2.git && \
    cd urg_node2 && git submodule update --remote
	
### install joystick tester (added by khkim)
RUN sudo apt update && sudo apt install -y jstest-gtk 
RUN mkdir -p .config/jstest-gtk

### install prerequisites and Intel realsense camera driver (added by khkim)
#RUN sudo apt install -y libssl-dev xorg-dev libusb-1.0-0-dev usbutils libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev 
#RUN mkdir temp_ws && cd temp_ws && \
#    git clone https://github.com/IntelRealSense/librealsense.git && \
#    apt-get update && apt-get install -y --no-install-recommends udev && \
#    sudo mkdir -p /etc/udev/rules.d && \
#    cd librealsense && mkdir build && cd build && \
#    cmake ../ -DFORCE_RSUSB_BACKEND=ON -DBUILD_PYTHON_BINDINGS:bool=true -DPYTHON_EXECUTABLE=/usr/bin/python3 \
#    -DCMAKE_BUILD_TYPE=release -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true -DBUILD_WITH_CUDA:bool=true \
#    -DCMAKE_INSTALL_PREFIX=/opt/ros/humble && \
#    make -j6 && sudo make install && \
#    cp ../config/99-realsense-libusb.rules /etc/udev/rules.d/ && \
#    cd ~/ && rm -rf temp_ws 

# --- Intel RealSense (librealsense) build & udev rule ---
USER root
RUN set -euxo pipefail && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        git build-essential cmake pkg-config python3-dev \
        udev libusb-1.0-0-dev usbutils \
        libssl-dev xorg-dev libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /etc/udev/rules.d && \
    git clone --depth=1 https://github.com/IntelRealSense/librealsense.git /tmp/librealsense && \
    cmake -S /tmp/librealsense -B /tmp/librealsense/build \
          -DFORCE_RSUSB_BACKEND=ON \
          -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 \
          -DBUILD_EXAMPLES=ON -DBUILD_GRAPHICAL_EXAMPLES=ON \
          -DBUILD_WITH_CUDA=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/opt/ros/humble && \
    cmake --build /tmp/librealsense/build -j"$(nproc)" && \
    cmake --install /tmp/librealsense/build && \
    install -m 0644 /tmp/librealsense/config/99-realsense-libusb.rules \
                    /etc/udev/rules.d/99-realsense-libusb.rules && \
    udevadm control --reload-rules || true && udevadm trigger || true && \
    rm -rf /tmp/librealsense
# 필요하면 여기서 다시 일반 사용자로 복귀
USER misys


### install f1tenth_system
RUN cd f1tenth_ws/src && \
    git clone https://github.com/goodash2one/f1tenth_system.git -b humble-devel && \
    cd f1tenth_system && rmdir ackermann_mux teleop_tools vesc

### vesc_to_odom error fix
RUN sed -i "102s/-state/state/" f1tenth_ws/src/vesc/vesc_ackermann/src/vesc_to_odom.cpp

### QoS setting
RUN sed -i "184s/RELIABLE/BEST_EFFORT/" f1tenth_ws/src/teleop_tools/joy_teleop/joy_teleop/joy_teleop.py

### </install drivers>


## clone repo
RUN git clone https://github.com/f1tenth/f1tenth_gym.git && \
    git clone https://github.com/goodash2one/Raceline-Optimization.git && \
    cd f1tenth_ws/src && \
    git clone https://github.com/goodash2one/f1tenth_gym_ros.git && \
    git clone https://github.com/goodash2one/slam_toolbox.git && \
    git clone https://github.com/goodash2one/particle_filter.git && \
    git clone https://github.com/goodash2one/bringup.git && \
    git clone https://github.com/IntelRealSense/realsense-ros.git -b ros2-master 

## clone packages from CL2-UWaterloo/f1tenth_ws/src
RUN cd f1tenth_ws/src && git init && \
    git config core.sparseCheckout true && \
    git remote add origin https://github.com/goodash2one/CL2-UWaterloo.git && \
    echo "src/pure_pursuit" >> .git/info/sparse-checkout && \
    echo "src/safety_node" >> .git/info/sparse-checkout && \
    git pull origin main && rm -rf .git/ && mv src CL2-UWaterloo && \
    cd CL2-UWaterloo && git init && \
    git config user.name $UNAME && git config user.email "you@example.com" && \
    git add . && git commit -m "clone packages from CL2-UWaterloo/f1tenth_ws/src"

## clone packages from derekhanbaliq/f1tenth-software-stack
RUN cd f1tenth_ws/src && git init && \
    git config core.sparseCheckout true && \
    git remote add origin https://github.com/derekhanbaliq/f1tenth-software-stack.git && \
    echo "mpc" >> .git/info/sparse-checkout && \
    git pull origin main && rm -rf .git/ && \
    cd mpc && rm .DS_Store && mkdir racelines && git init && \
    git config user.name $UNAME && git config user.email "you@example.com" && \
    git add . && git commit -m "clone packages from derekhanbaliq/f1tenth-software-stack"

## install f1tenth_gym && configuring
RUN cd f1tenth_gym && pip3 install -e .
RUN sed -i "45s/user/$UNAME/" f1tenth_ws/src/f1tenth_gym_ros/config/sim.yaml

## added by yhhong and khkim
RUN sed -i "30s/\/drive/drive/; \
            35s/\/opp_drive/opp_drive/" \
            f1tenth_ws/src/f1tenth_gym_ros/config/sim.yaml

## added by yhhong
## adding a slam_toolbox config file for offline mapping in simulation
RUN cd f1tenth_ws/src/slam_toolbox/config/ && \
    cp mapper_params_offline.yaml mapper_params_offline_sim.yaml && \
    sed -i "13s/odom_frame: odom/odom_frame: sim/; 14s/map_frame: map/map_frame: slam_map/; 15s/base_link/ego_racecar\/base_link/; 16s/\/scan/\/sim\/scan/" mapper_params_offline_sim.yaml

## added by yhhong
## adding a slam_toolbox launch file for offline mapping in simulation
RUN cp f1tenth_ws/src/slam_toolbox/launch/offline_launch.py f1tenth_ws/src/slam_toolbox/launch/offline_launch_sim.py && \
    sed -i "\
             11s/mapper_params_offline/mapper_params_offline_sim/; \ 
            "\
            f1tenth_ws/src/slam_toolbox/launch/offline_launch_sim.py

## build range_libc python wrapper
RUN sudo pip install cython && \
    cd f1tenth_ws/src/particle_filter && \
    sed -i "14s/cddt/rmgpu/" config/localize.yaml && \
    sed -i '/-DCMAKE_C_COMPILER/d' range_libc/pywrapper/compile_with_cuda.sh && \
    sed -i '/-DCMAKE_CXX_COMPILER/d' range_libc/pywrapper/compile_with_cuda.sh && \
    cd range_libc/pywrapper && ./compile_with_cuda.sh

# deprecated
# edit requirements.txt for aarch64
RUN sed -i "1s/1.18.1/1.19.5/; \
            5s/3.5.1/3.5.5/; \
            6s/1.3.3/1.5.4/; \
            7s/0.23.1/0.24.2/" \
        Raceline-Optimization/requirements.txt

# added by yhhong and khkim
RUN sed -i "17s/0.1/0.15/" Raceline-Optimization/params/f110.ini

## setup venv for Raceline-Optimization
RUN cd Raceline-Optimization && \
    python3.8 -m venv raceline && \
    source raceline/bin/activate && \
    pip install -r requirements.txt && \
    pip install ipykernel notebook pyqt6 && \
    python -m ipykernel install --user --name raceline && \
    deactivate

## configure pure_pursuit
RUN sed -i "s/user/$UNAME/g" f1tenth_ws/src/CL2-UWaterloo/pure_pursuit/config/sim_config.yaml
RUN sed -i "s/user/$UNAME/g" f1tenth_ws/src/CL2-UWaterloo/pure_pursuit/config/config.yaml

## configure mpc
RUN sed -i "\
            83s/levine_2nd/levine_full/; \
            86s/if/# if/; \
            87s/\"\/drive\"/\"\/auto\"/; \
            92s/if/if not/; \
            105s/csv_data/mpc/; \
            106s/'\/'/'\/racelines\/'/; \
            166s/if/if not/; \
            176s/if/if not/; \
            177s/if/if not/; \
            180s/if/if not/; \
            20s/.*/from rclpy.qos import QoSProfile/; \
            95s/1/QoSProfile(depth=1, reliability=2)/; \
            # parameter tuning
            # 385s/2/3/; \
            # 26s/8/12/; \
            39s/\[13.5, 13.5, 5.5, 13.0\]/\[50.0, 50.0, 10.0, 0.0\]/; \
            43s/\[13.5, 13.5, 5.5, 13.0\]/\[50.0, 50.0, 10.0, 0.0\]/; \
            " \
            f1tenth_ws/src/mpc/scripts/mpc_node.py

# added by yhhong and khkim
RUN sed -i "26s/8/6/; \
            39s/\[50.0, 50.0, 10.0, 0.0\]/\[100.0, 100.0, 0.0, 0.0\]/; \
            43s/\[50.0, 50.0, 10.0, 0.0\]/\[100.0, 100.0, 0.0, 0.0\]/; \
            87s/\/auto/\/sim\/drive/; \
            95s/reliability=2/reliability=1/" \
        f1tenth_ws/src/mpc/scripts/mpc_node.py

# added by yhhong and khkim to disable safety_node for joy control
RUN sed -i "156s/ld/# ld/" \
            f1tenth_ws/src/f1tenth_system/f1tenth_stack/launch/bringup_launch.py

# ## copy samples
# COPY --chown=$UNAME ./rosbag f1tenth_ws/rosbag
# COPY --chown=$UNAME ./pseudomap f1tenth_ws/pseudomap
# COPY --chown=$UNAME ./raceline f1tenth_ws/raceline
# RUN cp f1tenth_ws/pseudomap/* f1tenth_ws/src/particle_filter/maps && \
#     cp f1tenth_ws/pseudomap/* Raceline-Optimization/maps && \
#     cp f1tenth_ws/raceline/*_light.csv f1tenth_ws/src/CL2-UWaterloo/pure_pursuit/racelines && \
#     cp f1tenth_ws/raceline/*_full.csv f1tenth_ws/src/mpc/racelines

## added by yhhong
## turn off the plotting options of main_globaltraj_f110.py, Raceline Optimization program 
RUN sed -i "\
             56s/True/False/; \ 
             57s/True/False/; \ 
             59s/True/False/; \ 
             60s/True/False/; \ 
            "\ 
            Raceline-Optimization/main_globaltraj_f110.py

## check dependencies
RUN sudo apt update && cd f1tenth_ws && \
    sudo pip install meson ninja && \
    rosdep install -i --from-path src --ignore-src --rosdistro humble --skip-keys=librealsense2 -r -y || true
    #rosdep install -i --from-path src --ignore-src --rosdistro humble -r -y

# ackermann_msgs 를 소스로 추가 (ros2 브랜치)
RUN cd f1tenth_ws/src && \
    git clone https://github.com/ros-drivers/ackermann_msgs.git -b ros2

# diagnostic_updater (diagnostics 스택) 를 소스로 추가
# -> ackermann_mux 가 find_package(diagnostic_updater) 로 요구
RUN cd f1tenth_ws/src && \
    git clone https://github.com/ros/diagnostics.git -b ros2


## colcon-build workspace
RUN source /opt/ros/humble/setup.bash && \
    cd f1tenth_ws && colcon build

#수정 시작------------------------------------------------------------    
RUN grep -rl "script-dir" /home/$UNAME/f1tenth_ws | xargs sed -i 's/script-dir/script_dir/g' && \
    grep -rl "install-scripts" /home/$UNAME/f1tenth_ws | xargs sed -i 's/install-scripts/install_scripts/g'


### 0. robot_localization(EKF) 패키지 설치(added by seoknam)
RUN sudo apt-get update && \
    sudo apt-get install -y ros-humble-robot-localization


### 1. forza_ws 디렉토리 생성 및 race_stack 클론(seoknam)

# .netrc 파일 복사 (권한 조정 필수)
COPY .netrc /root/.netrc
RUN sudo chmod 600 /root/.netrc 



# 사용자 및 레포 설정
ARG UNAME=misys
ARG RACE_STACK_REPO="jeonseoknam/MAR-Misys-Autonomous-Racing-"
ARG RACE_STACK_BRANCH="full_tiny_final"

# 캐시 무효화를 위한 ARG
ARG CACHE_BREAKER=1
RUN echo "Cache breaker = $CACHE_BREAKER"

# race_stack clone
# root에서 clone 후 소유권 이전(.netrc 파일 사용 위함)
USER root
ENV HOME=/root

RUN set -euxo pipefail && \
    mkdir -p /home/misys/forza_ws && \
    rm -rf /home/misys/forza_ws/race_stack && \
    apt-get update && apt-get install -y --no-install-recommends git ca-certificates && \
    GIT_CURL_VERBOSE=1 git clone --depth=1 --recurse-submodules -b ${RACE_STACK_BRANCH} \
      https://github.com/${RACE_STACK_REPO}.git \
      /home/misys/forza_ws/race_stack && \
    chown -R misys:misys /home/misys/forza_ws/race_stack
    
# 다시 misys 사용자로 전환
USER $UNAME
ENV HOME=/home/$UNAME
WORKDIR /home/$UNAME    
          
### 2. post_create_command.sh 수정 (src 제거 반영)
RUN sed -i '2a USERNAME=$(whoami)' /home/$UNAME/forza_ws/race_stack/.install_utils/post_create_command.sh && \
    sed -i 's|~/ws|/home/$(whoami)/forza_ws/race_stack|g' /home/$UNAME/forza_ws/race_stack/.install_utils/post_create_command.sh && \
    sed -i 's|/home/\$USERNAME/ws|/home/'$UNAME'/forza_ws|g' /home/$UNAME/forza_ws/race_stack/.install_utils/post_create_command.sh && \
    sed -i 's|ws/src|forza_ws|g' /home/$UNAME/forza_ws/race_stack/.install_utils/post_create_command.sh 

### 3. post_create_command.sh 실행
RUN bash /home/$UNAME/forza_ws/race_stack/.install_utils/post_create_command.sh
### 4. ros-humble-asio-cmake-module 설치
RUN sudo apt-get update && sudo apt-get install -y ros-humble-asio-cmake-module &&\
    sudo apt install -y ros-humble-serial-driver
### 5. filterpy 설치
RUN pip install filterpy    
RUN pip install gymnasium==0.29.1
### 6. numpy 1.24.4로 재설치
RUN pip install numpy==1.24.4 --force-reinstall

# --- PyTorch install (auto-arch) ---
RUN python3 -m pip install --upgrade pip && \
    arch="$(dpkg --print-architecture)" && \
    if [ "$arch" = "arm64" ] || [ "$arch" = "aarch64" ]; then \
        echo "[INFO] Detected $arch (Jetson/L4T). Installing PyTorch from NVIDIA JP v60 index..." && \
        python3 -m pip install --no-cache-dir --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v60 \
            "torch==2.*" "torchvision==0.*"; \
    else \
        echo "[INFO] Detected $arch (non-Jetson). Installing CPU-only wheels from PyTorch index..." && \
        python3 -m pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu \
            "torch==2.*" "torchvision==0.*"; \
    fi

### 8. f1tenth_ws용 .activate_f1tenth.sh 생성 
RUN echo '#!/bin/bash' > /home/$UNAME/f1tenth_ws/.activate_f1tenth.sh && \
    echo 'TARGET_PATH="/home/misys/f1tenth_gym/gym"' >> /home/$UNAME/f1tenth_ws/.activate_f1tenth.sh && \
    echo 'echo "[INFO] Setting f110_gym to use f1tenth_ws"' >> /home/$UNAME/f1tenth_ws/.activate_f1tenth.sh && \
    echo 'echo "$TARGET_PATH" > ~/.local/lib/python3.10/site-packages/easy-install.pth' >> /home/$UNAME/f1tenth_ws/.activate_f1tenth.sh && \
    chmod +x /home/$UNAME/f1tenth_ws/.activate_f1tenth.sh


### 9. forza_ws용 .activate_forza.sh 생성
RUN echo '#!/bin/bash' > /home/$UNAME/forza_ws/race_stack/.activate_forza.sh && \
    echo 'TARGET_PATH="/home/misys/forza_ws/race_stack/base_system/f110_simulator/f1tenth_gym/gym   ' >> /home/$UNAME/forza_ws/race_stack/.activate_forza.sh && \
    echo '/home/misys/forza_ws/race_stack/planner/global_planner/global_planner/global_racetrajectory_optimization"' >> /home/$UNAME/forza_ws/race_stack/.activate_forza.sh && \
    echo 'echo "[INFO] Setting f110_gym to use forza_ws"' >> /home/$UNAME/forza_ws/race_stack/.activate_forza.sh && \
    echo 'echo "$TARGET_PATH" > ~/.local/lib/python3.10/site-packages/easy-install.pth' >> /home/$UNAME/forza_ws/race_stack/.activate_forza.sh && \
    chmod +x /home/$UNAME/forza_ws/race_stack/.activate_forza.sh

RUN pip3 install -r /home/misys/forza_ws/race_stack/.install_utils/python_req.txt && \
    pip3 install quadprog~=0.1.11

# --- ofc 패키지를 forza_ws에 추가 ---
ARG OFC_CACHE_BUST=0
RUN echo "OFC_CACHE_BUST=$OFC_CACHE_BUST" >/dev/null && \
    cd /home/$UNAME/forza_ws/race_stack && \
    rm -rf ofc && \
    git clone https://github.com/skylight722/ofc.git ofc

# --- TensorFlow 설치 ---
RUN sudo python3 -m pip install \
    tensorflow==2.15.0

# --- controller_enabled.yaml 추가 ---
RUN cat <<EOF > /home/$UNAME/forza_ws/race_stack/stack_master/config/controller_enabled.yaml
tln_inference:
  ros__parameters:
    enabled: false

ftg_controller:
  ros__parameters:
    enabled: false

ofc_joy_controller:
  ros__parameters:
    enabled: true

EOF


RUN source /opt/ros/humble/setup.bash &&\
    cd forza_ws/race_stack && colcon build
##수정 끝----------------------------------------------------------------------------------------------------------------------------2025.07.17

RUN echo "PATH=\$PATH:/home/$UNAME/.local/bin" >> .bashrc
RUN echo "alias underlay=\"source /opt/ros/humble/setup.bash\"" >> .bashrc && \
    echo "alias overlay=\"source install/setup.bash\"" >> .bashrc
# RUN echo "export ROS_LOCALHOST_ONLY=1" >> .bashrc
# RUN echo "export ROS_DOMAIN_ID=4" >> .bashrc
RUN echo "export SDL_JOYSTICK_DEVICE=\"/dev/input/js0\"" >> .bashrc

WORKDIR /home/$UNAME

